import { useContext, useMemo, useState } from 'react';
import { Link, Route, Routes } from 'react-router-dom';
import { AppDataContext } from '../App';

function Home(){const items=[['perfil','Perfil del niño'],['accesibilidad','Accesibilidad'],['rutinas','Rutinas'],['necesidades','Necesidades'],['cambio','Cambio de planes'],['detonantes','Registro de detonantes'],['progreso','Progreso']];return <div className='grid md:grid-cols-2 gap-3'>{items.map(([p,l])=><Link key={p} to={p} className='p-4 border rounded-xl bg-white'>{l}</Link>)}</div>}
function Perfil(){const {data,setData}=useContext(AppDataContext);const p=data.profile;return <div><h2>Perfil del niño</h2><input value={p.nickname} onChange={e=>setData(d=>({...d,profile:{...d.profile,nickname:e.target.value}}))} placeholder='Nombre' className='border p-2 m-1'/><input value={p.age} onChange={e=>setData(d=>({...d,profile:{...d.profile,age:e.target.value}}))} placeholder='Edad' className='border p-2 m-1'/></div>}
function Acc(){const {data,setData,reset,clear}=useContext(AppDataContext); const a=data.accessibility; return <div><h2>Preferencias de accesibilidad</h2>{[['lowStimulus','Modo bajo estímulo'],['soundEnabled','Sonidos'],['voiceEnabled','Voz'],['showTextWithImages','Texto junto imágenes'],['imagesOnly','Solo imágenes']].map(([k,l])=><label key={k} className='block'><input type='checkbox' checked={(a as any)[k]} onChange={e=>setData(d=>({...d,accessibility:{...d.accessibility,[k]:e.target.checked}}))}/>{l}</label>)}<button onClick={reset}>Restaurar datos ejemplo</button><button onClick={()=>setData(d=>({...d,progress:{...d.progress,routinesCompleted:0,emotionsLogged:0,needsUsed:0,calmZoneUsed:0,painReports:0,planChangesViewed:0,achievements:[]}}))}>Reiniciar progreso</button><button onClick={clear}>Borrar configuración local</button></div>}
function Rutinas(){const {data,setData}=useContext(AppDataContext);const [name,setName]=useState(''); return <div><h2>Editor de rutinas</h2><input value={name} onChange={e=>setName(e.target.value)} placeholder='Nueva rutina'/><button onClick={()=>setData(d=>({...d,routines:[...d.routines,{id:Date.now().toString(),name,tag:'especial',activities:[]}]}))}>Crear</button>{data.routines.map(r=><div key={r.id} className='border p-2 my-2'>{r.name} <button onClick={()=>setData(d=>({...d,routines:d.routines.filter(x=>x.id!==r.id)}))}>Eliminar</button></div>)}</div>}
function NeedsEdit(){const {data,setData}=useContext(AppDataContext);return <div><h2>Necesidades</h2>{data.needs.map(n=><label key={n.id} className='block'><input type='checkbox' checked={n.active} onChange={()=>setData(d=>({...d,needs:d.needs.map(x=>x.id===n.id?{...x,active:!x.active}:x)}))}/>{n.name}</label>)}</div>}
function ChangeEdit(){const {data,setData}=useContext(AppDataContext); return <div><h2>Cambio de planes</h2>{data.changePlans.map(c=><div key={c.id} className='border p-2 my-2'>{c.before} → {c.now}<button onClick={()=>setData(d=>({...d,changePlans:d.changePlans.map(x=>({...x,active:x.id===c.id}))}))}>Activar</button></div>)}</div>}
function Trigger(){const {data,setData}=useContext(AppDataContext); const [event,setEvent]=useState('Llanto'); const [before,setBefore]=useState('Ruido'); const [helped,setHelped]=useState('Silencio'); const summary=useMemo(()=>({total:data.triggerLogs.length}),[data.triggerLogs]); return <div><h2>Registro de detonantes</h2><button onClick={()=>setData(d=>({...d,triggerLogs:[{id:Date.now().toString(),date:new Date().toISOString(),event,before,helped},...d.triggerLogs]}))}>Guardar</button><p>Este registro puede ayudarte a observar patrones y compartir información útil con profesionales, maestros o cuidadores.</p><p>Total: {summary.total}</p>{data.triggerLogs.map(t=><div key={t.id}>{t.date} - {t.before} - {t.helped}</div>)}</div>}
function Progreso(){const {data}=useContext(AppDataContext);return <pre>{JSON.stringify(data.progress,null,2)}</pre>}

export default function(){return <Routes><Route path='/' element={<Home/>}/><Route path='perfil' element={<Perfil/>}/><Route path='accesibilidad' element={<Acc/>}/><Route path='rutinas' element={<Rutinas/>}/><Route path='necesidades' element={<NeedsEdit/>}/><Route path='cambio' element={<ChangeEdit/>}/><Route path='detonantes' element={<Trigger/>}/><Route path='progreso' element={<Progreso/>}/></Routes>}
