import { useContext, useMemo, useState } from 'react';
import { Link, Route, Routes } from 'react-router-dom';
import { AppDataContext } from '../App';

function Shell({ title, children }: any) { return <div className='space-y-4'><h2 className='text-3xl font-bold'>{title}</h2><div className='card-lumi'>{children}</div></div>; }
function Home() { const items = [['perfil', 'Perfil del niño'], ['accesibilidad', 'Accesibilidad'], ['rutinas', 'Rutinas'], ['necesidades', 'Necesidades'], ['cambio', 'Cambio de planes'], ['detonantes', 'Registro de detonantes'], ['progreso', 'Progreso']]; return <div className='grid md:grid-cols-2 gap-4'>{items.map(([p, l]) => <Link key={p} to={p} className='p-5 rounded-2xl border bg-white hover:bg-slate-50'>{l}</Link>)}</div>; }
function Perfil() { const { data, setData } = useContext(AppDataContext); const p = data.profile; return <Shell title='Perfil del niño'><div className='grid md:grid-cols-2 gap-3'><input value={p.nickname} onChange={e => setData(d => ({ ...d, profile: { ...d.profile, nickname: e.target.value } }))} placeholder='Nombre o apodo' className='border p-3 rounded-xl' /><input value={p.age} onChange={e => setData(d => ({ ...d, profile: { ...d.profile, age: e.target.value } }))} placeholder='Edad' className='border p-3 rounded-xl' /><input value={p.favoriteThing} onChange={e => setData(d => ({ ...d, profile: { ...d.profile, favoriteThing: e.target.value } }))} placeholder='Animal/objeto favorito' className='border p-3 rounded-xl' /></div></Shell>; }
function Acc() { const { data, setData, reset, clear } = useContext(AppDataContext); const a = data.accessibility; return <Shell title='Preferencias de accesibilidad'>{[['lowStimulus', 'Modo bajo estímulo'], ['soundEnabled', 'Sonidos'], ['voiceEnabled', 'Voz'], ['showTextWithImages', 'Texto junto imágenes'], ['imagesOnly', 'Solo imágenes']].map(([k, l]) => <label key={k} className='block py-1'><input type='checkbox' checked={(a as any)[k]} onChange={e => setData(d => ({ ...d, accessibility: { ...d.accessibility, [k]: e.target.checked } }))} /> {l}</label>)}<div className='flex flex-wrap gap-2 mt-4'><button onClick={reset} className='px-3 py-2 rounded-xl bg-blue-50'>Restaurar datos de ejemplo</button><button onClick={() => setData(d => ({ ...d, progress: { ...d.progress, routinesCompleted: 0, emotionsLogged: 0, needsUsed: 0, calmZoneUsed: 0, painReports: 0, planChangesViewed: 0, achievements: [] } }))} className='px-3 py-2 rounded-xl bg-amber-50'>Reiniciar progreso</button><button onClick={clear} className='px-3 py-2 rounded-xl bg-red-50'>Borrar configuración local</button></div></Shell>; }
function Rutinas() { const { data, setData } = useContext(AppDataContext); const [name, setName] = useState(''); return <Shell title='Editor de rutinas'><div className='flex gap-2 mb-3'><input value={name} onChange={e => setName(e.target.value)} placeholder='Nueva rutina' className='border p-2 rounded-xl flex-1' /><button onClick={() => setData(d => ({ ...d, routines: [...d.routines, { id: Date.now().toString(), name, tag: 'especial', activities: [] }] }))} className='px-3 rounded-xl bg-green-100'>Crear rutina</button></div>{data.routines.map(r => <div key={r.id} className='flex justify-between border rounded-xl p-3 my-2'><span>{r.name}</span><button onClick={() => setData(d => ({ ...d, routines: d.routines.filter(x => x.id !== r.id) }))}>Eliminar</button></div>)}</Shell>; }
function NeedsEdit() { const { data, setData } = useContext(AppDataContext); return <Shell title='Personalizar necesidades'>{data.needs.map(n => <label key={n.id} className='block py-1'><input type='checkbox' checked={n.active} onChange={() => setData(d => ({ ...d, needs: d.needs.map(x => x.id === n.id ? { ...x, active: !x.active } : x) }))} /> {n.name} <span className='text-xs text-slate-500'>({n.category})</span></label>)}</Shell>; }
function ChangeEdit() { const { data, setData } = useContext(AppDataContext); return <Shell title='Cambio de planes'>{data.changePlans.map(c => <div key={c.id} className='border rounded-xl p-3 my-2'><p>Antes: {c.before} / Ahora: {c.now}</p><button onClick={() => setData(d => ({ ...d, changePlans: d.changePlans.map(x => ({ ...x, active: x.id === c.id })) }))} className='px-3 py-1 rounded-lg bg-purple-100 mt-1'>Activar cambio</button></div>)}</Shell>; }
function Trigger() { const { data, setData } = useContext(AppDataContext); const [event, setEvent] = useState('Llanto'); const [before, setBefore] = useState('Ruido'); const [helped, setHelped] = useState('Silencio'); const summary = useMemo(() => ({ total: data.triggerLogs.length }), [data.triggerLogs]); return <Shell title='Registro de detonantes'><div className='grid md:grid-cols-3 gap-2'><select value={event} onChange={e => setEvent(e.target.value)} className='border p-2 rounded-xl'><option>Llanto</option><option>Gritos</option><option>Se frustró</option></select><select value={before} onChange={e => setBefore(e.target.value)} className='border p-2 rounded-xl'><option>Ruido</option><option>Cambio de rutina</option><option>Hambre</option></select><select value={helped} onChange={e => setHelped(e.target.value)} className='border p-2 rounded-xl'><option>Silencio</option><option>Descanso</option><option>Agua</option></select></div><button onClick={() => setData(d => ({ ...d, triggerLogs: [{ id: Date.now().toString(), date: new Date().toISOString(), event, before, helped }, ...d.triggerLogs] }))} className='mt-3 px-3 py-2 rounded-xl bg-lumi-soft-green'>Guardar registro</button><p className='text-sm mt-3'>Este registro puede ayudarte a observar patrones y compartir información útil con profesionales, maestros o cuidadores.</p><p className='font-bold mt-2'>Total de registros: {summary.total}</p>{data.triggerLogs.map(t => <div key={t.id} className='text-sm border-t pt-2 mt-2'>{t.date} · {t.before} · {t.helped}</div>)}</Shell>; }
function Progreso() { const { data } = useContext(AppDataContext); return <Shell title='Progreso simple'><div className='grid md:grid-cols-3 gap-3'>{Object.entries(data.progress).filter(([k]) => k !== 'achievements').map(([k, v]) => <div key={k} className='p-4 rounded-2xl bg-slate-50'><p className='text-xs uppercase'>{k}</p><p className='text-2xl font-bold'>{String(v)}</p></div>)}</div></Shell>; }

export default function () { return <Routes><Route path='/' element={<Home />} /><Route path='perfil' element={<Perfil />} /><Route path='accesibilidad' element={<Acc />} /><Route path='rutinas' element={<Rutinas />} /><Route path='necesidades' element={<NeedsEdit />} /><Route path='cambio' element={<ChangeEdit />} /><Route path='detonantes' element={<Trigger />} /><Route path='progreso' element={<Progreso />} /></Routes>; }
